/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/build-assets-manifest.mjs — do not edit by hand.
 * Source: ls public/images/characters/*.jpg + public/videos/characters/*.mp4
 * Re-run: npm run optimize:assets
 */
export type CharacterEntry = {
  name: string;
  image: string;
  video?: string;
};

export const generatedCharacters: CharacterEntry[] = [
  { name: "HELM", image: "/images/characters/05_helm_rider.jpg", video: "/videos/characters/vid_05_helm.mp4" },
  { name: "MORI", image: "/images/characters/06_mori_forest.jpg", video: "/videos/characters/vid_06_mori.mp4" },
  { name: "REEF", image: "/images/characters/09_reef_deep_sea.jpg" },
  { name: "STATIC", image: "/images/characters/11_static_tvhead.jpg", video: "/videos/characters/vid_11_static.mp4" },
  { name: "ORCHID", image: "/images/characters/12_orchid_alien.jpg", video: "/videos/characters/vid_12_orchid.mp4" },
  { name: "EMBER", image: "/images/characters/14_ember_fire.jpg", video: "/videos/characters/vid_14_ember.mp4" },
  { name: "POLLEN", image: "/images/characters/19_pollen_mushroom.jpg", video: "/videos/characters/vid_19_pollen.mp4" },
  { name: "HALO", image: "/images/characters/22_halo_angel.jpg", video: "/videos/characters/vid_22_halo.mp4" },
  { name: "KOI", image: "/images/characters/23_koi_water.jpg" },
  { name: "ZEPHYR", image: "/images/characters/25_zephyr_cloud.jpg" },
  { name: "GUMM", image: "/images/characters/26_gumm_gummy.jpg" },
  { name: "BISCUIT", image: "/images/characters/27_biscuit_dog.jpg" },
  { name: "CHOMP", image: "/images/characters/28_chomp_dino.jpg" },
  { name: "DUSTY", image: "/images/characters/29_dusty_bunny.jpg" },
  { name: "RAGDOLL", image: "/images/characters/29_dusty_ragdoll.jpg" },
  { name: "SOCK", image: "/images/characters/30_sock_puppet.jpg" },
  { name: "CLAY", image: "/images/characters/36_clay_sculpture.jpg" },
  { name: "SALT FLAT", image: "/images/characters/salt flat.jpg" },
];
