/* tokens.json -> system/tokens.css
 *
 *   node scripts/build-tokens.mjs
 *
 * tokens.json is the source of truth, in W3C Design Tokens format so it also
 * imports straight into Figma. This writes the CSS custom properties the ad
 * templates actually use, so the two can't drift.
 *
 * Sizes in the `size` and `space` groups — and card/shot radii — are authored
 * against the 1920px reference canvas and emitted as calc(N * var(--u)), where
 * --u is set per ad from its own width. So one number holds at every size.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const src = JSON.parse(readFileSync(join(root, 'system/tokens.json'), 'utf8'));

/* groups whose px values are canvas-relative and get scaled by --u */
const SCALED = new Set(['size', 'space', 'radius']);

const px = (v) => Number(String(v).replace('px', ''));
const isFixed = (t) => t?.$extensions?.sweat?.fixed === true;

const lines = [];
const say = (s = '') => lines.push(s);

const value = (group, name, token) => {
  const v = token.$value;
  if (Array.isArray(v)) return v.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ');
  if (SCALED.has(group) && !isFixed(token) && String(v).endsWith('px')) {
    return `calc(${px(v)} * var(--u))`;
  }
  return String(v);
};

/* longest name in a group, so the emitted CSS lines up in a column */
const pad = (entries) => Math.max(...entries.map(([k]) => k.length));

say('/* ------------------------------------------------------------------');
say('   Sweat Strategies — design tokens');
say('   GENERATED by scripts/build-tokens.mjs from system/tokens.json.');
say('   Edit the JSON, not this file.');
say('   ------------------------------------------------------------------ */');
say();
say('@font-face {');
say('  font-family: "Manrope";');
say('  src: url("fonts/Manrope-VariableFont_wght.ttf") format("truetype");');
say('  font-weight: 200 800;');
say('  font-display: block;');
say('}');
say();
say(':root {');
say('  /* --u is the scale unit and every size below is a multiple of it.');
say('     --cw  the canvas width in pixels, as a bare number.');
say('     --uref  the width at which the sizes below read at face value.');
say('');
say('     Leave --uref at 1920 and the ad is a straight proportional scale of');
say('     a slide. Ads are viewed at a fraction of a projected slide, so the');
say('     templates drop it to 1080 — which makes the numbers land as authored');
say('     on a 1080-wide ad, running the type larger relative to the frame. */');
say('  --cw: 1920;');
say('  --uref: 1920;');
say('  --u: calc(var(--cw) * 1px / var(--uref));');
say();

for (const [group, body] of Object.entries(src)) {
  if (group.startsWith('$')) continue;

  const entries = Object.entries(body).filter(([k]) => !k.startsWith('$'));
  if (!entries.length) continue;

  const w = pad(entries);
  if (body.$description) say(`  /* ${body.$description} */`);

  for (const [name, token] of entries) {
    const prop = `--${group}-${name}`.padEnd(group.length + w + 3);
    const note = token.$description ? `  /* ${token.$description} */` : '';
    say(`  ${prop}: ${value(group, name, token)};${note}`);
  }
  say();
}

while (lines.at(-1) === '') lines.pop();  // the group loop leaves one behind
say('}');

const out = `${lines.join('\n')}\n`;
writeFileSync(join(root, 'system/tokens.css'), out);
console.log(`wrote system/tokens.css  ${out.split('\n').length} lines`);
